// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlduimgtsfpqlscirnws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsZHVpbWd0c2ZwcWxzY2lybndzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4MTkyNzksImV4cCI6MjA1NDM5NTI3OX0.MXN6id4BUNmnucSpweAquIgmK26MKzsV5v4Z6GYUaJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);